### PR TITLE
AWS SDK version update

### LINKED ISSUE #9: IRSA support
Hi,

We're using KrakenD on our EKS environment and wanted to start using the Lambda triggering as well.
Our EKS environment uses [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) to get the necessary credentials for AWS services.

When we're trying to test Lambda triggering we're getting 403 errors although the IAM Role attacked to the Pod has the proper permissions.

I noticed that this module is uses aws-sdk-go v1.19.16 while the [minimal SDK version required](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html ) for IRSA to work is v1.23.13

We're unable to use API key and secret for security reasons. 

Can you please verify that this is the reason for our 403 errors, if so, it would be great if you could update the aws-sdk-go version.

### PR DESCRIPTION
**Pull request by boris154**
Closes #9 

- Updated aws-sdk-go version to the latest one (v1.44.24).
- Updated README with the proper lcoalstack parameters based on the official docs. Otherwise the tests didn't work on my local PC.
- Added logger to BackendFactory in `localstack_test.go`

Test ran successfully.

### CODE REVIEW

**Comment by kpacha** [comment]
nice!

can you fix the conflicts and update the pkgs from the krakendio group?

**Comment by boris154** [comment]
Hey @kpacha 
I did a back merge and resolved the conflicts.

**Review by kpacha — APPROVED** [review]

**Comment by kpacha** [comment]
@boris154 thanks for the contribution!

**Comment by boris154** [comment]
@kpacha Do you have an estimation on when this changes are going to be release to krakend-ce ?

**Comment by kpacha** [comment]
@boris154 it should be included into the v2.1.0, expected to be released at the end of september

**Pull request merged**
